### ISSUE TITLE
How does it work for text data?

### ISSUE THREAD

**Issue by rbhatia46** [dedupeio/dedupe#1020]
I was trying to dedup some addresses with this library ? I have a few basic questions - 

1. I see that there are a lot of different data types which are included in dedupe, but how does it work specifically for the text data(address in my case), I understand the active learning part, but internally what model is being used and what features are used for learning from text data ?

2. How many labeling samples are enough to generate a good performance, I know it might highly depend on use-case, but are there any rule of thumb which we should be aware about ?

Thanks

**Comment by NickCrews** [comment]
Hey @rbhatia46!

1. Have you read all of https://docs.dedupe.io/en/latest/how-it-works/How-it-works.html as well as https://docs.dedupe.io/en/latest/Variable-definition.html? It says at https://docs.dedupe.io/en/latest/Variable-definition.html#string-types that `String` types are compared using affine gap distance (but you can also use [a different string edit distance](https://docs.dedupe.io/en/latest/Variable-definition.html#optional-edit-distance)). So that's the feature that is getting used as a similarity metric. Or, in the next section, it says `Text` types are compared using cosine similarity. There is only one feature generated per variable, so if you want to try giving the model multiple features to learn from, then for instance you would give it both a Text and a String variable. Does that help?

2. Sorry, not gonna be able to be very exact here. If you only have a very small number of variables (and therefore small number of features), as you probably do with addresses, then it's not going to require many samples to learn the pattern. Example: For a single feature of edit distance, the model basically just has to learn a single threshold, below that edit distance is considered match, above that is non-match. We're not dealing with huge neural nets here, just a logistic regression. I think that's only gonna require like 10-20 samples. As you add more variables, you'll need more samples. Totally guessing here, with 4 variables maybe you want 60 pairs? Try with 20, then 40, then 60, and check the trend of your accuracy.

**Comment by NickCrews** [comment]
@fgregg maybe double check my intuition there

**Comment by rbhatia46** [comment]
Thanks for answering @NickCrews, it helps understand what I was looking for!

**Comment by fgregg** [comment]
thanks for fielding @NickCrews
