### ISSUE TITLE
OSError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by melvin15may** [dedupeio/dedupe#564]
I get the following error on running dedupe on Centos 6.9. Using csvdedupe to run it.

> Traceback (most recent call last):
  File "/usr/local/bin/csvdedupe", line 11, in <module>
    sys.exit(launch_new_instance())
  File "/usr/local/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 180, in launch_new_instance
    d.main()
  File "/usr/local/lib/python2.7/site-packages/csvdedupe/csvdedupe.py", line 127, in main
    threshold = deduper.threshold(unique_d, recall_weight=self.recall_weight)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 237, in threshold
    return self.thresholdBlocks(blocked_pairs, recall_weight)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 71, in thresholdBlocks
    self.num_cores)['score']
  File "/usr/local/lib/python2.7/site-packages/dedupe/core.py", line 212, in scoreDuplicates
    fillQueue(record_pairs_queue, records, n_map_processes)
  File "/usr/local/lib/python2.7/site-packages/dedupe/core.py", line 245, in fillQueue
    chunk = list(itertools.islice(iterable, int(chunk_size)))
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 253, in <genexpr>
    pairs = (combinations(sorted(block), 2) for block in blocks)
  File "/usr/local/lib/python2.7/site-packages/dedupe/api.py", line 286, in _blockData
    os.remove(file_path)
OSError: [Errno 2] No such file or directory: '/tmp/tmp72kdip'

I have went through [api.py](https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py). In line [#1075](https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L1074), the temporary file is removed. Then again the file is removed in line [#286](https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L286). 
A work-around that I use is to create the temp file again after line #1076. Is this a correct approach?

**Comment by yuanxu-li** [comment]
I have the same problem here...

**Comment by androsxc** [comment]
Hello, I have had the same problem and tried to find a workaround without success. It seems this is related to shelve module which manages the temporary databases. There are cases where shelve creates three files with extensions .dir, .dat, .bak, instead of a temporary file without extension.  I am not sure what triggers this behavior of shelve but  I am assuming it may be the OS or even the database size (?).

(I am using dedupe on pyspark and originally I thought it would be an issue with distributed systems, where a process would try to close or remove a file that had been already removed by another process but I think shelve is the issue).

You can try to monitor the files created under /tmp/ during execution and look if only files without extension are created, or if you also see three copies of a file with the three extensions I mentioned. 

These may be of help:
https://bytes.com/topic/python/answers/477418-shelve-bak-dat-dir-files

https://books.google.de/books?id=q8W3WQbNWmkC&pg=PA24&lpg=PA24&dq=python+shelve+bak+dat+dir&source=bl&ots=Y89aaUkAYF&sig=xQYLJ3PWWj-eSzgqRJULXJf6j_w&hl=de&sa=X&ved=0ahUKEwjw9Z_N0ojVAhXjK5oKHZbyAx0Q6AEIcTAJ#v=onepage&q=python%20shelve%20bak%20dat%20dir&f=false

https://inventwithpython.com/blog/2012/05/03/implement-a-save-game-feature-in-python-with-the-shelve-module/

**Comment by androsxc** [comment]
@melvin15may  When you mention line 1075, do you mean the  _temp_shelve() function?
If so, could you explain your workaround in more detail please? Thanks!

**Comment by fgregg** [comment]
Thanks for the detailed report @androsxc, this is helpful.

**Comment by yuanxu-li** [comment]
@androsxc 

Use monkey patch as a workaround. Because the problem only occurs with `_temp_shelve`, then we simply replace this function with one that we define and make it right.

```python
import dedupe
import dedupe.api

import tempfile
import shelve
import pickle

def _temp_shelve():
    fd, file_path = tempfile.mkstemp()
    os.close(fd)

    try:
        shelf = shelve.open(
            file_path,
            'n',
            protocol=pickle.HIGHEST_PROTOCOL
        )
    except Exception as e:
        if 'db type could not be determined' in str(e):
            os.remove(file_path)
            shelf = shelve.open(
                file_path,
                'n',
                protocol=pickle.HIGHEST_PROTOCOL
            )

        else:
            raise

    if not os.path.exists(file_path):
        os.mknod(file_path)

    return shelf, file_path


dedupe.api._temp_shelve = _temp_shelve
```

**Comment by androsxc** [comment]
@fgregg, a pleasure, will try to come back with more insights.
@yuanxu-li , thanks for the fast response, Ill try it now.

**Comment by fgregg** [comment]
@androsxc, could you take a look at https://github.com/dedupeio/dedupe/pull/590 and see if it addresses this problem

**Comment by fgregg** [comment]
@androsxc could you take a look at this?

**Comment by androsxc** [comment]
hello again, I will check it tomorrow and let you know. Btw,  the workaround from @yuanxu-li  worked for me as a temporal fix.
