### ISSUE TITLE
Huge Temp file being created during dedupe csv example

### ISSUE THREAD

**Issue by wkniffin** [dedupeio/dedupe#581]
Hello all!

I've used the csv example to run a deduping with my own dataset which is about 140k records. I keep running into a problem with running out of disk space. There is a limited amount on my machine, and I noticed a temp file keeps growing like crazy until space runs out.

The error which stops the execution of the code is:
"OSError: [Errno 28] No space left on device

I'm running the example on a Windows machine.

Is there any way to point the file to another location? Or to simply stop the file from being created in the first place?

Thanks!

**Comment by fgregg** [comment]
hmm... it's a good idea for the temp file to be able to set the location of the tempfile, but if csvdedupe wasn't writing to a file it would have to take up almost the same amount of space in memory.

**Comment by wkniffin** [comment]
Where is the temp file directory set in the code? Is it possible for me to simply specify a location that I know has enough disk space?

**Comment by fgregg** [comment]
it would require a little surgery in the upstream library. https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L1058

i

**Comment by wkniffin** [comment]
All I had to do was change the file_path!
```python
shelf = shelve.open('E:\\python\\temp', 'n',
                                      protocol=pickle.HIGHEST_PROTOCOL)
```
Now the file is in the drive I want and it is called temp.dat.

Thanks for the help!

**Comment by fgregg** [comment]
I'm glad that worked for you. We'll want to add a feature to set the path of the temp file more easily.

**Comment by liufuyang** [comment]
@wkniffin  may I ask how fast it runs for your 140k records?

For me I have a 30K records to match agains to, and if I use the default dbm way it takes more than 10 minutes to match on, for example a 2 entries records.
During the matching you could see output like this:
```
[2017-06-29 20:43:56,841: INFO/PoolWorker-1] 10000, 182.5327482 seconds
[2017-06-29 20:53:40,909: INFO/PoolWorker-1] 20000, 758.9884932 seconds
```
which I believe is the output from https://github.com/dedupeio/dedupe/blob/master/dedupe/blocking.py#L42

As so far we have enough memory, I had to change the code here to let the blocking happen in a 
dictionary in memory :
https://github.com/dedupeio/dedupe/blob/master/dedupe/api.py#L1072

Basically, instead of returning `shelf`, return an empty python dictionary:
```python
def _temp_shelve():
    fd, file_path = tempfile.mkstemp()
    os.close(fd)

    try:
        shelf = shelve.open(file_path, 'n',
                                      protocol=pickle.HIGHEST_PROTOCOL)
    except Exception as e:
        if 'db type could not be determined' in str(e):
            os.remove(file_path)
            shelf = shelve.open(file_path, 'n',
                                protocol=pickle.HIGHEST_PROTOCOL)
        else:
            raise

    return {}, file_path # return python dictionary instead of shelf
```
This will make the blocking and matching process takes lots of memory but it can finish a 2 entries matching against 30K records in a few seconds.

@wkniffin it would be nice if you could share some info on how fast it runs for you.

@fgregg would you also mind take a look at my situation above and perhaps you know how fast should dedupe runs for a one or two entries case when matching against 30K records? (Or is it normal for me that it runs so slow when using `shelve`?)
And is there a simpler way (not changing source code) if I want all this happen in memory but not on hard drive? (I assume `shelve` will create some dictionary like object on hard drive...)

**Comment by rajivgrover009** [comment]
i am still getting "No space left on device error". I am trying to figure out where do i change the file path.

**Comment by finnythekid** [comment]
Bit late but thought I would add to this. You can redirect the default tmp directory python looks for with tempfile.mkstemp by setting the TMPDIR, TEMP or TMP environment variables to the path you would like to use. Changing these will avoid making any changes in the code.

e.g. in linux: 

`export TMP=/path/to/tempdir`

**Comment by greghor** [comment]
Hi all, I have a similar issue. I try to link records between two datasets of about 100k and 400k records, respectively. The sizes of the temporary files are huge, more than 500GB!!! Is this a normal behavior?

**Comment by DanHelfman** [comment]
I am also experiencing the issue of a temp file growing to an unmanageably large size.  I am working with approximately 830k records.  Is there a way to limit the default temp file from growing so large, and if so, how?
