### ISSUE TITLE
clarify Gazetteer.sample function 

### ISSUE THREAD

**Issue by FlorianHoppe** [dedupeio/dedupe#735]
Could you please explain what the 'sample' function of the 'Gazetteer' class is doing? I have a pretty good grasp what the 'train' does but dont understand why a 'sample' step is needed beforehand. 
I wonder whether it would be okay to give both function the same set of messy and canonical data.

**Comment by adriennefranke** [comment]
In order to train the Gazetteer, you need to first feed it a sample of records. From the [documentation](https://docs.dedupe.io/en/latest/API-documentation.html#Gazetteer.train) regarding the train function, it says "Requires that adequate training data has been already been provided."

Also, here's an [example of a Gazetteer](https://github.com/dedupeio/dedupe-examples/tree/master/gazetteer_example) - I found this really helpful when building one myself.

**Comment by FlorianHoppe** [comment]
Thanks! But I wonder exactly about what's an "adequate training data" set. I have no problems to get the model working, but now I want to fine tune it by - maybe - changing the data set.

So I would like to better understand what this sample function does in order to better decide what data I have to provide for that.

**Comment by fgregg** [comment]
this would be better for stackoverflow or the mailinglist.
