### ISSUE TITLE
[clarification] different score for elements in same cluster

### ISSUE THREAD

**Issue by jyjyj** [dedupeio/dedupe#741]
hi, would like to understand the rationale for giving some elements that are grouped together in a cluster different scores. i am basically wondering: in a cluster with elements A, B, C, what does it mean that A matches with 0.99 confidence while B and C match with 0.7 confidence?

referencing this issue (https://github.com/dedupeio/dedupe/issues/321), is there a way to return the centroid of the cluster in a vector (or some other) format, and return the distance of each record to the centre of its cluster? i'm assuming the centroid is not one of the elements in particular, but if it is, perhaps another indicator showing which element is the centroid is useful as well.

thanks!

**Comment by fgregg** [comment]
The scores for individual records are kind of an unusual animal.

Let a cluster have N elements.

For record i of a cluster, the score is `1 - sqrt(sum_j(dist_ij**2)/(N - 1))`. This is similar to standard deviation.

You could treat the record with the highest scores as the centroid.

The main reason why we use this score function instead of say, average distance, is that it allows us to combine the individual scores to calculate the standard deviation of the entire cluster, which is a reasonable measure of cluster quality

`std(cluster) = sum_i((1 - score_i)**2) / 2`

This all makes the assumption that the pairwise probability scores can be turned into a euclidean distance. This is not fully true, but it is what is is.
