### ISSUE TITLE
childProcessError when running deduce.partition in a Jupyter Notebook on OSX

### ISSUE THREAD

**Issue by wrathagom** [dedupeio/dedupe#835]
I am running dedupe in a Jupyter notebook on Mac. When I run this line of code:

```
groups = deduper.partition(data, threshold=.7)
```

I get this error at the same place each time, 360000:

```
INFO:dedupe.blocking:340000, 10.0376252 seconds
INFO:dedupe.blocking:350000, 10.3528052 seconds
INFO:dedupe.blocking:360000, 10.6705842 seconds
---------------------------------------------------------------------------
ChildProcessError                         Traceback (most recent call last)
 in 
----> 1 groups = deduper.partition(data, threshold=.7)

~/opt/anaconda3/lib/python3.7/site-packages/dedupe/api.py in partition(self, data, threshold)
    168         """
    169         pairs = self.pairs(data)
--> 170         pair_scores = self.score(pairs)
    171         clusters = self.cluster(pair_scores, threshold)
    172 

~/opt/anaconda3/lib/python3.7/site-packages/dedupe/api.py in score(self, pairs)
    104                                            self.data_model,
    105                                            self.classifier,
--> 106                                            self.num_cores)
    107         except RuntimeError:
    108             raise RuntimeError('''

~/opt/anaconda3/lib/python3.7/site-packages/dedupe/core.py in scoreDuplicates(record_pairs, data_model, classifier, num_cores)
    247     result = result_queue.get()
    248     if isinstance(result, Exception):
--> 249         raise ChildProcessError
    250 
    251     if result:

ChildProcessError: 
```

it looks like the num_cores setting had something to do with it, I've tried with that setting set to `None`, `1`, and `2` and all have the same outcome.

I found [this issue](https://github.com/dedupeio/dedupe/issues/499), which sounded somewhat familiar. So in case it helps here is the output of:

```
import numpy
print(numpy.__config__.__dict__)
```

```
{'__name__': 'numpy.__config__', '__doc__': None, '__package__': 'numpy', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fa3571b59d0>, '__spec__': ModuleSpec(name='numpy.__config__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fa3571b59d0>, origin='/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/numpy/__config__.py'), '__file__': '/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/numpy/__config__.py', '__cached__': '/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/numpy/__pycache__/__config__.cpython-37.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'hasattr': <built-in function hasattr>, 'hash': <built-in function hash>, 'hex': <built-in function hex>, 'id': <built-in function id>, 'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x7fa356643ed0>>, 'isinstance': <built-in function isinstance>, 'issubclass': <built-in function issubclass>, 'iter': <built-in function iter>, 'len': <built-in function len>, 'locals': <built-in function locals>, 'max': <built-in function max>, 'min': <built-in function min>, 'next': <built-in function next>, 'oct': <built-in function oct>, 'ord': <built-in function ord>, 'pow': <built-in function pow>, 'print': <built-in function print>, 'repr': <built-in function repr>, 'round': <built-in function round>, 'setattr': <built-in function setattr>, 'sorted': <built-in function sorted>, 'sum': <built-in function sum>, 'vars': <built-in function vars>, 'None': None, 'Ellipsis': Ellipsis, 'NotImplemented': NotImplemented, 'False': False, 'True': True, 'bool': <class 'bool'>, 'memoryview': <class 'memoryview'>, 'bytearray': <class 'bytearray'>, 'bytes': <class 'bytes'>, 'classmethod': <class 'classmethod'>, 'complex': <class 'complex'>, 'dict': <class 'dict'>, 'enumerate': <class 'enumerate'>, 'filter': <class 'filter'>, 'float': <class 'float'>, 'frozenset': <class 'frozenset'>, 'property': <class 'property'>, 'int': <class 'int'>, 'list': <class 'list'>, 'map': <class 'map'>, 'object': <class 'object'>, 'range': <class 'range'>, 'reversed': <class 'reversed'>, 'set': <class 'set'>, 'slice': <class 'slice'>, 'staticmethod': <class 'staticmethod'>, 'str': <class 'str'>, 'super': <class 'super'>, 'tuple': <class 'tuple'>, 'type': <class 'type'>, 'zip': <class 'zip'>, '__debug__': True, 'BaseException': <class 'BaseException'>, 'Exception': <class 'Exception'>, 'TypeError': <class 'TypeError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'StopIteration': <class 'StopIteration'>, 'GeneratorExit': <class 'GeneratorExit'>, 'SystemExit': <class 'SystemExit'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ImportError': <class 'ImportError'>, 'ModuleNotFoundError': <class 'ModuleNotFoundError'>, 'OSError': <class 'OSError'>, 'EnvironmentError': <class 'OSError'>, 'IOError': <class 'OSError'>, 'EOFError': <class 'EOFError'>, 'RuntimeError': <class 'RuntimeError'>, 'RecursionError': <class 'RecursionError'>, 'NotImplementedError': <class 'NotImplementedError'>, 'NameError': <class 'NameError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'IndentationError': <class 'IndentationError'>, 'TabError': <class 'TabError'>, 'LookupError': <class 'LookupError'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'ValueError': <class 'ValueError'>, 'UnicodeError': <class 'UnicodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'AssertionError': <class 'AssertionError'>, 'ArithmeticError': <class 'ArithmeticError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'OverflowError': <class 'OverflowError'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'SystemError': <class 'SystemError'>, 'ReferenceError': <class 'ReferenceError'>, 'MemoryError': <class 'MemoryError'>, 'BufferError': <class 'BufferError'>, 'Warning': <class 'Warning'>, 'UserWarning': <class 'UserWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'FutureWarning': <class 'FutureWarning'>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'BytesWarning': <class 'BytesWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'ConnectionError': <class 'ConnectionError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'FileExistsError': <class 'FileExistsError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'InterruptedError': <class 'InterruptedError'>, 'PermissionError': <class 'PermissionError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'TimeoutError': <class 'TimeoutError'>, 'open': <built-in function open>, 'copyright': Copyright (c) 2001-2019 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object., '__IPYTHON__': True, 'display': <function display at 0x7fa355065830>, '__pybind11_internals_v3_clang_libcpp_cxxabi1002__': <capsule object NULL at 0x7fa359712db0>, 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fa356643b90>>}, '__all__': ['get_info', 'show'], 'os': <module 'os' from '/Users/calebkeller/opt/anaconda3/lib/python3.7/os.py'>, 'sys': <module 'sys' (built-in)>, 'extra_dll_dir': '/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/numpy/.libs', 'blas_mkl_info': {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/calebkeller/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/calebkeller/opt/anaconda3/include']}, 'blas_opt_info': {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/calebkeller/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/calebkeller/opt/anaconda3/include']}, 'lapack_mkl_info': {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/calebkeller/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/calebkeller/opt/anaconda3/include']}, 'lapack_opt_info': {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/calebkeller/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/calebkeller/opt/anaconda3/include']}, 'get_info': <function get_info at 0x7fa3571b07a0>, 'show': <function show at 0x7fa3571b0dd0>}
```

**Comment by wrathagom** [comment]
When I change num_cores to 0 I get a different error:

```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/dedupe/core.py", line 182, in mergeScores
    raise
RuntimeError: No active exception to reraise

Exception in thread Thread-59:
Traceback (most recent call last):
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/dedupe/core.py", line 127, in __call__
    filtered_pairs: Optional[Tuple] = self.fieldDistance(record_pairs)
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/dedupe/core.py", line 142, in fieldDistance
    distances = self.data_model.distances(records)
  File "/Users/calebkeller/opt/anaconda3/lib/python3.7/site-packages/dedupe/datamodel.py", line 83, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 111, in affinegap.affinegap.normalizedAffineGapDistance
  File "affinegap/affinegap.pyx", line 130, in affinegap.affinegap.normalizedAffineGapDistance
ZeroDivisionError: float division
```

**Comment by fjsj** [comment]
@wrathagom 
Do you have empty strings in your textual data?
If so, replace them with None and the affinegap error should be gone. Using num_cores != 0 is hiding the real error which is the affinegap one.

**Comment by thomasadams-velocityglobal** [comment]
@fjsj like this df.replace('', np.nan, inplace=True) ? It's not getting rid of the error for me.

**Comment by fjsj** [comment]
@thomasadams-velocityglobal 
`np.nan` is not a Python `None`. After doing that, try https://stackoverflow.com/a/54403705/145349

**Comment by thomasadams-velocityglobal** [comment]
@fjsj darn that didn't work still getting the error. 
![image](https://user-images.githubusercontent.com/60484140/91236337-e664dd00-e6f4-11ea-846f-185eaa9ea84c.png)

**Comment by fjsj** [comment]
@thomasadams-velocityglobal This could be specific of pandas_dedupe. I never used it, so I can't help you with this one.
If you can provide a small reproducible example with regular dedupe, I can check.

**Comment by rajatbagchi** [comment]
Hey Guys!
I've been getting same error while running the code in Databricks with more than 22,000 input data set. I'm getting clustered records and code is working fine with less than 22000 input records. And I'm using Dedupe.dedupe not Pandas_Dedupe.
Please let me know if you need more information regarding the issue.
I'm eagerly looking for some help to resolve this issue.

**Comment by lycenok** [comment]
could it be because for the smaller datasets (less than 22000) there were no cases with empty strings, @rajatbagchi ?

**Comment by rajatbagchi** [comment]
No, there were empty strings in the smaller dataset also.

**Comment by fjsj** [comment]
Folks, remember to try with a single core, otherwise your real error will be masked by `ChildProcessError`.

And if the empty strings in your dataset are not blocked together, they won't be scored and you won't see the `ZeroDivisionError` error.

**Comment by marianadpl** [comment]
Hi everyone, 

I am getting the Child Processor error. I have no empty strings. It was working up until previous month. Any hints? 

clustered_dupes = matcher.partition(data_d, threshold=0.5)
Traceback (most recent call last):

  File "<ipython-input-58-22ec1bb638e8>", line 1, in <module>
    clustered_dupes = matcher.partition(data_d, threshold=0.5)

  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\api.py", line 170, in partition
    pair_scores = self.score(pairs)

  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\api.py", line 103, in score
    matches = core.scoreDuplicates(pairs,

  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\core.py", line 256, in scoreDuplicates
    raise ChildProcessError

ChildProcessError

the more deailed version when I run the script from Anaconda prompt: 

Traceback (most recent call last):
  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\api.py", line 103, in score
    matches = core.scoreDuplicates(pairs,
  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\core.py", line 244, in scoreDuplicates
    process.start()
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\depaulm\Miniconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\depaulm\Miniconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\depaulm\Miniconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\depaulm\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "T:\Life_GI_Dedupe\Test Scripts\Dedupe_Life_GI_test_Mari_vs.py", line 203, in <module>
    clustered_dupes = deduper.partition(data_d, threshold=0.5)
  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\api.py", line 170, in partition
    pair_scores = self.score(pairs)
  File "C:\Users\depaulm\Miniconda3\lib\site-packages\dedupe\api.py", line 108, in score
    raise RuntimeError('''
RuntimeError:
                You need to either turn off multiprocessing or protect
                the calls to the Dedupe methods with a
                `if __name__ == '__main__'` in your main module, see
                https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods
Traceback (most recent call last):
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\depaulm\\AppData\\Local\\Temp\\1\\tmphwsuzo6s\\blocks.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\depaulm\Miniconda3\lib\tempfile.py", line 803, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\depaulm\\AppData\\Local\\Temp\\1\\tmphwsuzo6s\\blocks.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\depaulm\Miniconda3\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\Users\depaulm\Miniconda3\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\depaulm\Miniconda3\lib\tempfile.py", line 818, in _cleanup
    cls._rmtree(name)
  File "C:\Users\depaulm\Miniconda3\lib\tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\depaulm\Miniconda3\lib\tempfile.py", line 806, in onerror
    cls._rmtree(path)
  File "C:\Users\depaulm\Miniconda3\lib\tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 596, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\depaulm\Miniconda3\lib\shutil.py", line 593, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\depaulm\\AppData\\Local\\Temp\\1\\tmphwsuzo6s\\blocks.db'

**Comment by fjsj** [comment]
@marianadpl I think the answer is in your stacktrace:
```
You need to either turn off multiprocessing or protect
the calls to the Dedupe methods with a
if __name__ == '__main__' in your main module
```

Have you tried that?

**Comment by marianadpl** [comment]
I tried the if__name__ method, but didn't work. I'm not sure though how to turn off the multiprocessing method:

Did this from os library:
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['NUMEXPR_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'

Didn't work either.

**Comment by fjsj** [comment]
To disable multiprocessing, use `num_cores` argument. See:
- https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.Dedupe
- https://docs.dedupe.io/en/latest/API-documentation.html#dedupe.StaticDedupe
