### ISSUE TITLE
_format_search_results Assertion Error

### ISSUE THREAD

**Issue by monicatao** [dedupeio/dedupe#841]
Hi, is there a reason why you added "assert a is not None" in the _format_search_results function in latest release. Because now I always get assertion error while running gazette model.
Please advise. Thank you!

**Comment by fgregg** [comment]
i added it to take advantage of static typing, but indeed `a` should never be `None`.  Can you prepare a reproducible example?

**Comment by fgregg** [comment]
@felixpoege can you post a reproducible example

**Comment by felixpoege** [comment]
Would be super annoying to extract that dedupe component out of a large workflow, isn't there any pointer what to search for?
I varied the set of messy records (small random subset of the full one) and the the error occurs every time. I changed the code of `api.py` to print `a` before asserting, the result is `[ ]`. Same for `result'.
In another dedupe component, which then is a `Dedupe' type (not `Gazetteer` as this one) runs flawlessly.

For now, I changed the `api.py` code so that if `a is None`, the `yield` and `seen.add(a)` part is skipped - that seemed to work for now.
